config/routes.rb
FridayLunch::Application.routes.draw do
  resources :lunches do
    resources :options
    resources :orders
  end

  root 'lunches#new'

end

app/models/lunch.rb
class Lunch < ActiveRecord::Base
    has_many :options
    has_many :orders
end

app/models/option.rb
class Option < ActiveRecord::Base
    belongs_to :lunch
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :lunch
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lunches_controller.rb
class LunchesController < ApplicationController
  before_action :set_lunch, only: [:show, :edit, :update, :destroy]

  # GET /lunches
  # GET /lunches.json
  def index
    @lunches = Lunch.all
  end

  # GET /lunches/1
  # GET /lunches/1.json
  def show
    @options = @lunch.options
    @orders_count = Hash.new
    
    @options.each do |option|
        @orders_count[option] = @lunch.orders.where(order: option.id)
    end
    
      
  end

  # GET /lunches/new
  def new
    @lunch = Lunch.new
  end

  # GET /lunches/1/edit
  def edit
  end

  # POST /lunches
  # POST /lunches.json
  def create
    @lunch = Lunch.new(lunch_params)

    respond_to do |format|
      if @lunch.save
        format.html { redirect_to @lunch, notice: 'Lunch was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lunch }
      else
        format.html { render action: 'new' }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lunches/1
  # PATCH/PUT /lunches/1.json
  def update
    respond_to do |format|
      if @lunch.update(lunch_params)
        format.html { redirect_to @lunch, notice: 'Lunch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lunches/1
  # DELETE /lunches/1.json
  def destroy
    @lunch.destroy
    respond_to do |format|
      format.html { redirect_to lunches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lunch
      @lunch = Lunch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lunch_params
      params.require(:lunch).permit(:restaurant, :date)
    end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
    def create
        @lunch = Lunch.find(params[:lunch_id])
        @option = @lunch.options.create(option_params)
        redirect_to lunch_path(@lunch)    
    end
    
    private
    
        def option_params
            params.require(:option).permit(:option, :description)
        end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def create
        puts params
        @lunch = Lunch.find(params[:lunch_id])
        @order = @lunch.orders.create(order_params)
        redirect_to lunch_path(@lunch)    
    end
    
    private
    
        def order_params
            params.require(:order).permit(:name, :order)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lunches_helper.rb
module LunchesHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FridayLunch</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <%= yield %>

    <%= debug(params) if Rails.env.development? %>
</div>


</body>
</html>

app/views/lunches/_form.html.erb
<%= form_for(@lunch) do |f| %>
  <% if @lunch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lunch.errors.count, "error") %> prohibited this lunch from being saved:</h2>

      <ul>
      <% @lunch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
        
  <% end %>

  <div class="field">
    <%= f.label :restaurant %><br>
    <%= f.text_field :restaurant %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lunches/edit.html.erb
<h1>Editing lunch</h1>

<%= render 'form' %>

<%= link_to 'Show', @lunch %> |
<%= link_to 'Back', lunches_path %>

app/views/lunches/index.html.erb
<h1>Listing lunches</h1>

<table>
  <thead>
    <tr>
      <th>Restaurant</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lunches.each do |lunch| %>
      <tr>
        <td><%= lunch.restaurant %></td>
        <td><%= lunch.date %></td>
        <td><%= link_to 'Show', lunch %></td>
        <td><%= link_to 'Edit', edit_lunch_path(lunch) %></td>
        <td><%= link_to 'Destroy', lunch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lunch', new_lunch_path %>

app/views/lunches/new.html.erb
<h1>New lunch</h1>

<p>
    Hey Sophie, just put in the name of the restaurant and the date for the lunch. On the next page you'll be able to set the options that people can have.
</p>

<%= render 'form' %>

<%= link_to 'Back', lunches_path %>

app/views/lunches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Restaurant:</strong>
  <%= @lunch.restaurant %>
</p>

<p>
  <strong>Date:</strong>
  <%= @lunch.date %>
</p>

<h2>
  Options on the Menu
</h2>

<em>
    Pick your choice and add your name to the order. MMMmmmm Lunch :).
</em>

<p>
    
</p>

<%= form_for([@lunch, @lunch.orders.build]) do |f| %>
  
  <% @options.each do |option| %>
    <p>
       <%= f.radio_button :order, option.id %> <%= option.option %> - <em><%=  option.description %></em>
    </p>
  <% end %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %> 
  </p>
  
  <div class="actions">
    <%= f.submit :Order %>
  </div>
  
<% end %>

<h2>Stats</h2>
<% @orders_count.each do |option, orders| %>
    <p>
        <%= option.option %>: <%= orders.count %>
    </p>
<% end %>

<h2>
  Add an option to the menu <small> - this bit is for Sophie</small>
</h2>

<%= form_for([@lunch, @lunch.options.build]) do |f| %>

  <div class="field">
    <%= f.label :option %><br>
    <%= f.text_field :option %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_lunch_path(@lunch) %> |
<%= link_to 'Back', lunches_path %>